# Generated by Django 4.0.5 on 2022-06-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Seeker'), ('2', 'Owner'), ('3', 'Admin')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
